name: 'What about 60 '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48019
title: What About 60 and 50 and 40 and 30 and 20
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a0b1c'
    - '#f5fdf9'
    - '#60aae9'
    - '#934f02'
    - '#ffcb5b'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
