name: 'What about 60 '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53862
title: What About 60 and 50 and 40 and 30 and 20
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#646462'
    - '#ffeccc'
    - '#9cc253'
    - '#a5c8ff'
  brandStrength: 0
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
