name: 'What about 60 '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48019
title: What About 60 and 50 and 40 and 30 and 20
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acaeba'
    - '#3b5e00'
    - '#819266'
    - '#dfdfe1'
    - '#ce9700'
  brandStrength: 0
  lightness: 0.8099119397811592
  saturation: 0.32706476165913045
  rhythmicContrast: 0.38009263621643186
purpose: []
