name: 'What about 60 '
favicon: null
layout_spectrum: 0.5711348548065871
typography_spectrum: 0.6162893257569522
title: What About 60 and 50 and 40 and 30 and 20
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7970444222446531
  lightness: 0.8099119397811592
  saturation: 0.32706476165913045
  rhythmicContrast: 0.38009263621643186
purpose: []
